/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Locker,
  LockerInsertInput,
  LockerUpdateInput,
  LockerWithRelations,
  PaginatedLocker,
  PaginationQueryInput,
} from '../models/index';
import {
    LockerFromJSON,
    LockerToJSON,
    LockerInsertInputFromJSON,
    LockerInsertInputToJSON,
    LockerUpdateInputFromJSON,
    LockerUpdateInputToJSON,
    LockerWithRelationsFromJSON,
    LockerWithRelationsToJSON,
    PaginatedLockerFromJSON,
    PaginatedLockerToJSON,
    PaginationQueryInputFromJSON,
    PaginationQueryInputToJSON,
} from '../models/index';

export interface ApiLockersIdDeleteRequest {
    id: string;
}

export interface ApiLockersIdGetRequest {
    id: string;
}

export interface ApiLockersIdPutRequest {
    id: string;
    lockerUpdateInput?: LockerUpdateInput;
}

export interface ApiLockersPostRequest {
    lockerInsertInput?: LockerInsertInput;
}

export interface ApiLockersSearchPostRequest {
    paginationQueryInput?: PaginationQueryInput;
}

/**
 * 
 */
export class LockerApi extends runtime.BaseAPI {

    /**
     */
    async apiLockersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Locker>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lockers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LockerFromJSON));
    }

    /**
     */
    async apiLockersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Locker>> {
        const response = await this.apiLockersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLockersIdDeleteRaw(requestParameters: ApiLockersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiLockersIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lockers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiLockersIdDelete(requestParameters: ApiLockersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.apiLockersIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLockersIdGetRaw(requestParameters: ApiLockersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LockerWithRelations>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiLockersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lockers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LockerWithRelationsFromJSON(jsonValue));
    }

    /**
     */
    async apiLockersIdGet(requestParameters: ApiLockersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LockerWithRelations> {
        const response = await this.apiLockersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLockersIdPutRaw(requestParameters: ApiLockersIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Locker>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiLockersIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lockers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LockerUpdateInputToJSON(requestParameters['lockerUpdateInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LockerFromJSON(jsonValue));
    }

    /**
     */
    async apiLockersIdPut(requestParameters: ApiLockersIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Locker> {
        const response = await this.apiLockersIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLockersPostRaw(requestParameters: ApiLockersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Locker>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lockers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LockerInsertInputToJSON(requestParameters['lockerInsertInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LockerFromJSON(jsonValue));
    }

    /**
     */
    async apiLockersPost(requestParameters: ApiLockersPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Locker> {
        const response = await this.apiLockersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLockersSearchPostRaw(requestParameters: ApiLockersSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLocker>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lockers/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaginationQueryInputToJSON(requestParameters['paginationQueryInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLockerFromJSON(jsonValue));
    }

    /**
     */
    async apiLockersSearchPost(requestParameters: ApiLockersSearchPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLocker> {
        const response = await this.apiLockersSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
