/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiBranchesDeleteDeleteRequest
 */
export interface ApiBranchesDeleteDeleteRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiBranchesDeleteDeleteRequest
     */
    ids: Array<number>;
}

/**
 * Check if a given object implements the ApiBranchesDeleteDeleteRequest interface.
 */
export function instanceOfApiBranchesDeleteDeleteRequest(value: object): value is ApiBranchesDeleteDeleteRequest {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function ApiBranchesDeleteDeleteRequestFromJSON(json: any): ApiBranchesDeleteDeleteRequest {
    return ApiBranchesDeleteDeleteRequestFromJSONTyped(json, false);
}

export function ApiBranchesDeleteDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBranchesDeleteDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function ApiBranchesDeleteDeleteRequestToJSON(json: any): ApiBranchesDeleteDeleteRequest {
    return ApiBranchesDeleteDeleteRequestToJSONTyped(json, false);
}

export function ApiBranchesDeleteDeleteRequestToJSONTyped(value?: ApiBranchesDeleteDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

