/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Locker } from './Locker';
import {
    LockerFromJSON,
    LockerFromJSONTyped,
    LockerToJSON,
    LockerToJSONTyped,
} from './Locker';
import type { ApiLockersSearchGet200ResponseMeta } from './ApiLockersSearchGet200ResponseMeta';
import {
    ApiLockersSearchGet200ResponseMetaFromJSON,
    ApiLockersSearchGet200ResponseMetaFromJSONTyped,
    ApiLockersSearchGet200ResponseMetaToJSON,
    ApiLockersSearchGet200ResponseMetaToJSONTyped,
} from './ApiLockersSearchGet200ResponseMeta';

/**
 * 
 * @export
 * @interface ApiLockersSearchGet200Response
 */
export interface ApiLockersSearchGet200Response {
    /**
     * 
     * @type {Array<Locker>}
     * @memberof ApiLockersSearchGet200Response
     */
    data: Array<Locker>;
    /**
     * 
     * @type {ApiLockersSearchGet200ResponseMeta}
     * @memberof ApiLockersSearchGet200Response
     */
    meta: ApiLockersSearchGet200ResponseMeta;
}

/**
 * Check if a given object implements the ApiLockersSearchGet200Response interface.
 */
export function instanceOfApiLockersSearchGet200Response(value: object): value is ApiLockersSearchGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ApiLockersSearchGet200ResponseFromJSON(json: any): ApiLockersSearchGet200Response {
    return ApiLockersSearchGet200ResponseFromJSONTyped(json, false);
}

export function ApiLockersSearchGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLockersSearchGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LockerFromJSON)),
        'meta': ApiLockersSearchGet200ResponseMetaFromJSON(json['meta']),
    };
}

export function ApiLockersSearchGet200ResponseToJSON(json: any): ApiLockersSearchGet200Response {
    return ApiLockersSearchGet200ResponseToJSONTyped(json, false);
}

export function ApiLockersSearchGet200ResponseToJSONTyped(value?: ApiLockersSearchGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(LockerToJSON)),
        'meta': ApiLockersSearchGet200ResponseMetaToJSON(value['meta']),
    };
}

