/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLockersSearchGet200ResponseMeta
 */
export interface ApiLockersSearchGet200ResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof ApiLockersSearchGet200ResponseMeta
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ApiLockersSearchGet200ResponseMeta
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof ApiLockersSearchGet200ResponseMeta
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ApiLockersSearchGet200ResponseMeta
     */
    totalPages: number;
}

/**
 * Check if a given object implements the ApiLockersSearchGet200ResponseMeta interface.
 */
export function instanceOfApiLockersSearchGet200ResponseMeta(value: object): value is ApiLockersSearchGet200ResponseMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function ApiLockersSearchGet200ResponseMetaFromJSON(json: any): ApiLockersSearchGet200ResponseMeta {
    return ApiLockersSearchGet200ResponseMetaFromJSONTyped(json, false);
}

export function ApiLockersSearchGet200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLockersSearchGet200ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'totalPages': json['totalPages'],
    };
}

export function ApiLockersSearchGet200ResponseMetaToJSON(json: any): ApiLockersSearchGet200ResponseMeta {
    return ApiLockersSearchGet200ResponseMetaToJSONTyped(json, false);
}

export function ApiLockersSearchGet200ResponseMetaToJSONTyped(value?: ApiLockersSearchGet200ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

