/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { ApiLockersSearchGet200ResponseMeta } from './ApiLockersSearchGet200ResponseMeta';
import {
    ApiLockersSearchGet200ResponseMetaFromJSON,
    ApiLockersSearchGet200ResponseMetaFromJSONTyped,
    ApiLockersSearchGet200ResponseMetaToJSON,
    ApiLockersSearchGet200ResponseMetaToJSONTyped,
} from './ApiLockersSearchGet200ResponseMeta';

/**
 * 
 * @export
 * @interface ApiUsersSearchGet200Response
 */
export interface ApiUsersSearchGet200Response {
    /**
     * 
     * @type {Array<User>}
     * @memberof ApiUsersSearchGet200Response
     */
    data: Array<User>;
    /**
     * 
     * @type {ApiLockersSearchGet200ResponseMeta}
     * @memberof ApiUsersSearchGet200Response
     */
    meta: ApiLockersSearchGet200ResponseMeta;
}

/**
 * Check if a given object implements the ApiUsersSearchGet200Response interface.
 */
export function instanceOfApiUsersSearchGet200Response(value: object): value is ApiUsersSearchGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ApiUsersSearchGet200ResponseFromJSON(json: any): ApiUsersSearchGet200Response {
    return ApiUsersSearchGet200ResponseFromJSONTyped(json, false);
}

export function ApiUsersSearchGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersSearchGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserFromJSON)),
        'meta': ApiLockersSearchGet200ResponseMetaFromJSON(json['meta']),
    };
}

export function ApiUsersSearchGet200ResponseToJSON(json: any): ApiUsersSearchGet200Response {
    return ApiUsersSearchGet200ResponseToJSONTyped(json, false);
}

export function ApiUsersSearchGet200ResponseToJSONTyped(value?: ApiUsersSearchGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserToJSON)),
        'meta': ApiLockersSearchGet200ResponseMetaToJSON(value['meta']),
    };
}

