/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchInsertInput
 */
export interface BranchInsertInput {
    /**
     * 
     * @type {number}
     * @memberof BranchInsertInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BranchInsertInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchInsertInput
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof BranchInsertInput
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchInsertInput
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the BranchInsertInput interface.
 */
export function instanceOfBranchInsertInput(value: object): value is BranchInsertInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function BranchInsertInputFromJSON(json: any): BranchInsertInput {
    return BranchInsertInputFromJSONTyped(json, false);
}

export function BranchInsertInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchInsertInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'address': json['address'],
        'location': json['location'] == null ? undefined : json['location'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function BranchInsertInputToJSON(json: any): BranchInsertInput {
    return BranchInsertInputToJSONTyped(json, false);
}

export function BranchInsertInputToJSONTyped(value?: BranchInsertInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
    };
}

