/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Locker } from './Locker';
import {
    LockerFromJSON,
    LockerFromJSONTyped,
    LockerToJSON,
    LockerToJSONTyped,
} from './Locker';

/**
 * 
 * @export
 * @interface BranchWithRelations
 */
export interface BranchWithRelations {
    /**
     * 
     * @type {number}
     * @memberof BranchWithRelations
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelations
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelations
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelations
     */
    location: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelations
     */
    createdAt: string;
    /**
     * 
     * @type {Array<Locker>}
     * @memberof BranchWithRelations
     */
    lockers: Array<Locker>;
}

/**
 * Check if a given object implements the BranchWithRelations interface.
 */
export function instanceOfBranchWithRelations(value: object): value is BranchWithRelations {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lockers' in value) || value['lockers'] === undefined) return false;
    return true;
}

export function BranchWithRelationsFromJSON(json: any): BranchWithRelations {
    return BranchWithRelationsFromJSONTyped(json, false);
}

export function BranchWithRelationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchWithRelations {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'],
        'location': json['location'],
        'createdAt': json['createdAt'],
        'lockers': ((json['lockers'] as Array<any>).map(LockerFromJSON)),
    };
}

export function BranchWithRelationsToJSON(json: any): BranchWithRelations {
    return BranchWithRelationsToJSONTyped(json, false);
}

export function BranchWithRelationsToJSONTyped(value?: BranchWithRelations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
        'lockers': ((value['lockers'] as Array<any>).map(LockerToJSON)),
    };
}

