/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchUpdate
 */
export interface BranchUpdate {
    /**
     * 
     * @type {number}
     * @memberof BranchUpdate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdate
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdate
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdate
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the BranchUpdate interface.
 */
export function instanceOfBranchUpdate(value: object): value is BranchUpdate {
    return true;
}

export function BranchUpdateFromJSON(json: any): BranchUpdate {
    return BranchUpdateFromJSONTyped(json, false);
}

export function BranchUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'location': json['location'] == null ? undefined : json['location'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function BranchUpdateToJSON(json: any): BranchUpdate {
    return BranchUpdateToJSONTyped(json, false);
}

export function BranchUpdateToJSONTyped(value?: BranchUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
    };
}

