/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchInput
 */
export interface BranchInput {
    /**
     * 
     * @type {number}
     * @memberof BranchInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BranchInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchInput
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof BranchInput
     */
    location: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchInput
     */
    createdAt: string;
}

/**
 * Check if a given object implements the BranchInput interface.
 */
export function instanceOfBranchInput(value: object): value is BranchInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BranchInputFromJSON(json: any): BranchInput {
    return BranchInputFromJSONTyped(json, false);
}

export function BranchInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'],
        'location': json['location'],
        'createdAt': json['createdAt'],
    };
}

export function BranchInputToJSON(json: any): BranchInput {
    return BranchInputToJSONTyped(json, false);
}

export function BranchInputToJSONTyped(value?: BranchInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
    };
}

