/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchUpdateInput
 */
export interface BranchUpdateInput {
    /**
     * 
     * @type {number}
     * @memberof BranchUpdateInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateInput
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateInput
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateInput
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the BranchUpdateInput interface.
 */
export function instanceOfBranchUpdateInput(value: object): value is BranchUpdateInput {
    return true;
}

export function BranchUpdateInputFromJSON(json: any): BranchUpdateInput {
    return BranchUpdateInputFromJSONTyped(json, false);
}

export function BranchUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'location': json['location'] == null ? undefined : json['location'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function BranchUpdateInputToJSON(json: any): BranchUpdateInput {
    return BranchUpdateInputToJSONTyped(json, false);
}

export function BranchUpdateInputToJSONTyped(value?: BranchUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
    };
}

