/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LockerInput } from './LockerInput';
import {
    LockerInputFromJSON,
    LockerInputFromJSONTyped,
    LockerInputToJSON,
    LockerInputToJSONTyped,
} from './LockerInput';

/**
 * 
 * @export
 * @interface BranchWithRelationsInput
 */
export interface BranchWithRelationsInput {
    /**
     * 
     * @type {number}
     * @memberof BranchWithRelationsInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelationsInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelationsInput
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelationsInput
     */
    location: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithRelationsInput
     */
    createdAt: string;
    /**
     * 
     * @type {Array<LockerInput>}
     * @memberof BranchWithRelationsInput
     */
    lockers: Array<LockerInput>;
}

/**
 * Check if a given object implements the BranchWithRelationsInput interface.
 */
export function instanceOfBranchWithRelationsInput(value: object): value is BranchWithRelationsInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lockers' in value) || value['lockers'] === undefined) return false;
    return true;
}

export function BranchWithRelationsInputFromJSON(json: any): BranchWithRelationsInput {
    return BranchWithRelationsInputFromJSONTyped(json, false);
}

export function BranchWithRelationsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchWithRelationsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'],
        'location': json['location'],
        'createdAt': json['createdAt'],
        'lockers': ((json['lockers'] as Array<any>).map(LockerInputFromJSON)),
    };
}

export function BranchWithRelationsInputToJSON(json: any): BranchWithRelationsInput {
    return BranchWithRelationsInputToJSONTyped(json, false);
}

export function BranchWithRelationsInputToJSONTyped(value?: BranchWithRelationsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
        'lockers': ((value['lockers'] as Array<any>).map(LockerInputToJSON)),
    };
}

