/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchInsert
 */
export interface BranchInsert {
    /**
     * 
     * @type {number}
     * @memberof BranchInsert
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BranchInsert
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchInsert
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof BranchInsert
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchInsert
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the BranchInsert interface.
 */
export function instanceOfBranchInsert(value: object): value is BranchInsert {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function BranchInsertFromJSON(json: any): BranchInsert {
    return BranchInsertFromJSONTyped(json, false);
}

export function BranchInsertFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchInsert {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'address': json['address'],
        'location': json['location'] == null ? undefined : json['location'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function BranchInsertToJSON(json: any): BranchInsert {
    return BranchInsertToJSONTyped(json, false);
}

export function BranchInsertToJSONTyped(value?: BranchInsert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'location': value['location'],
        'createdAt': value['createdAt'],
    };
}

