/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Locker
 */
export interface Locker {
    /**
     * 
     * @type {number}
     * @memberof Locker
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    area: string | null;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    size: LockerSizeEnum;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    type: LockerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    lockType: LockerLockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    status: LockerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof Locker
     */
    userId: number | null;
    /**
     * 
     * @type {number}
     * @memberof Locker
     */
    branchId: number | null;
}


/**
 * @export
 */
export const LockerSizeEnum = {
    S: 's',
    M: 'm',
    L: 'l',
    Xl: 'xl'
} as const;
export type LockerSizeEnum = typeof LockerSizeEnum[keyof typeof LockerSizeEnum];

/**
 * @export
 */
export const LockerTypeEnum = {
    Standard: 'standard',
    Smart: 'smart'
} as const;
export type LockerTypeEnum = typeof LockerTypeEnum[keyof typeof LockerTypeEnum];

/**
 * @export
 */
export const LockerLockTypeEnum = {
    Key: 'key',
    Card: 'card',
    Pin: 'pin',
    Biometric: 'biometric'
} as const;
export type LockerLockTypeEnum = typeof LockerLockTypeEnum[keyof typeof LockerLockTypeEnum];

/**
 * @export
 */
export const LockerStatusEnum = {
    Available: 'available',
    InUse: 'in_use',
    Maintenance: 'maintenance',
    Broken: 'broken'
} as const;
export type LockerStatusEnum = typeof LockerStatusEnum[keyof typeof LockerStatusEnum];


/**
 * Check if a given object implements the Locker interface.
 */
export function instanceOfLocker(value: object): value is Locker {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    if (!('area' in value) || value['area'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('lockType' in value) || value['lockType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('branchId' in value) || value['branchId'] === undefined) return false;
    return true;
}

export function LockerFromJSON(json: any): Locker {
    return LockerFromJSONTyped(json, false);
}

export function LockerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locker {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lockerCode': json['lockerCode'],
        'area': json['area'],
        'size': json['size'],
        'type': json['type'],
        'lockType': json['lockType'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'userId': json['userId'],
        'branchId': json['branchId'],
    };
}

export function LockerToJSON(json: any): Locker {
    return LockerToJSONTyped(json, false);
}

export function LockerToJSONTyped(value?: Locker | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'area': value['area'],
        'size': value['size'],
        'type': value['type'],
        'lockType': value['lockType'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
        'branchId': value['branchId'],
    };
}

