/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Locker
 */
export interface Locker {
    /**
     * 
     * @type {number}
     * @memberof Locker
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Locker
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof Locker
     */
    userId: number;
}

/**
 * Check if a given object implements the Locker interface.
 */
export function instanceOfLocker(value: object): value is Locker {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LockerFromJSON(json: any): Locker {
    return LockerFromJSONTyped(json, false);
}

export function LockerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locker {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lockerCode': json['lockerCode'],
        'location': json['location'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'userId': json['userId'],
    };
}

export function LockerToJSON(json: any): Locker {
    return LockerToJSONTyped(json, false);
}

export function LockerToJSONTyped(value?: Locker | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'location': value['location'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
    };
}

