/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockerInput
 */
export interface LockerInput {
    /**
     * 
     * @type {number}
     * @memberof LockerInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    area: string | null;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    size: LockerInputSizeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    type: LockerInputTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    lockType: LockerInputLockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    status: LockerInputStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof LockerInput
     */
    userId: number | null;
    /**
     * 
     * @type {number}
     * @memberof LockerInput
     */
    branchId: number | null;
}


/**
 * @export
 */
export const LockerInputSizeEnum = {
    S: 's',
    M: 'm',
    L: 'l',
    Xl: 'xl'
} as const;
export type LockerInputSizeEnum = typeof LockerInputSizeEnum[keyof typeof LockerInputSizeEnum];

/**
 * @export
 */
export const LockerInputTypeEnum = {
    Standard: 'standard',
    Smart: 'smart'
} as const;
export type LockerInputTypeEnum = typeof LockerInputTypeEnum[keyof typeof LockerInputTypeEnum];

/**
 * @export
 */
export const LockerInputLockTypeEnum = {
    Key: 'key',
    Card: 'card',
    Pin: 'pin',
    Biometric: 'biometric'
} as const;
export type LockerInputLockTypeEnum = typeof LockerInputLockTypeEnum[keyof typeof LockerInputLockTypeEnum];

/**
 * @export
 */
export const LockerInputStatusEnum = {
    Available: 'available',
    InUse: 'in_use',
    Maintenance: 'maintenance',
    Broken: 'broken'
} as const;
export type LockerInputStatusEnum = typeof LockerInputStatusEnum[keyof typeof LockerInputStatusEnum];


/**
 * Check if a given object implements the LockerInput interface.
 */
export function instanceOfLockerInput(value: object): value is LockerInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    if (!('area' in value) || value['area'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('lockType' in value) || value['lockType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('branchId' in value) || value['branchId'] === undefined) return false;
    return true;
}

export function LockerInputFromJSON(json: any): LockerInput {
    return LockerInputFromJSONTyped(json, false);
}

export function LockerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockerInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lockerCode': json['lockerCode'],
        'area': json['area'],
        'size': json['size'],
        'type': json['type'],
        'lockType': json['lockType'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'userId': json['userId'],
        'branchId': json['branchId'],
    };
}

export function LockerInputToJSON(json: any): LockerInput {
    return LockerInputToJSONTyped(json, false);
}

export function LockerInputToJSONTyped(value?: LockerInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'area': value['area'],
        'size': value['size'],
        'type': value['type'],
        'lockType': value['lockType'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
        'branchId': value['branchId'],
    };
}

