/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockerUpdateInput
 */
export interface LockerUpdateInput {
    /**
     * 
     * @type {number}
     * @memberof LockerUpdateInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LockerUpdateInput
     */
    lockerCode?: string;
    /**
     * 
     * @type {string}
     * @memberof LockerUpdateInput
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof LockerUpdateInput
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof LockerUpdateInput
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof LockerUpdateInput
     */
    userId?: number;
}

/**
 * Check if a given object implements the LockerUpdateInput interface.
 */
export function instanceOfLockerUpdateInput(value: object): value is LockerUpdateInput {
    return true;
}

export function LockerUpdateInputFromJSON(json: any): LockerUpdateInput {
    return LockerUpdateInputFromJSONTyped(json, false);
}

export function LockerUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockerUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lockerCode': json['lockerCode'] == null ? undefined : json['lockerCode'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function LockerUpdateInputToJSON(json: any): LockerUpdateInput {
    return LockerUpdateInputToJSONTyped(json, false);
}

export function LockerUpdateInputToJSONTyped(value?: LockerUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'location': value['location'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
    };
}

