/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockerInsertInput
 */
export interface LockerInsertInput {
    /**
     * 
     * @type {number}
     * @memberof LockerInsertInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LockerInsertInput
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInsertInput
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInsertInput
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInsertInput
     */
    createdAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LockerInsertInput
     */
    userId?: number | null;
}

/**
 * Check if a given object implements the LockerInsertInput interface.
 */
export function instanceOfLockerInsertInput(value: object): value is LockerInsertInput {
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function LockerInsertInputFromJSON(json: any): LockerInsertInput {
    return LockerInsertInputFromJSONTyped(json, false);
}

export function LockerInsertInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockerInsertInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lockerCode': json['lockerCode'],
        'location': json['location'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function LockerInsertInputToJSON(json: any): LockerInsertInput {
    return LockerInsertInputToJSONTyped(json, false);
}

export function LockerInsertInputToJSONTyped(value?: LockerInsertInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'location': value['location'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
    };
}

