/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockerInsert
 */
export interface LockerInsert {
    /**
     * 
     * @type {number}
     * @memberof LockerInsert
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    area?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    size?: LockerInsertSizeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    type?: LockerInsertTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    lockType?: LockerInsertLockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    status?: LockerInsertStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerInsert
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof LockerInsert
     */
    userId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LockerInsert
     */
    branchId?: number | null;
}


/**
 * @export
 */
export const LockerInsertSizeEnum = {
    S: 's',
    M: 'm',
    L: 'l',
    Xl: 'xl'
} as const;
export type LockerInsertSizeEnum = typeof LockerInsertSizeEnum[keyof typeof LockerInsertSizeEnum];

/**
 * @export
 */
export const LockerInsertTypeEnum = {
    Standard: 'standard',
    Smart: 'smart'
} as const;
export type LockerInsertTypeEnum = typeof LockerInsertTypeEnum[keyof typeof LockerInsertTypeEnum];

/**
 * @export
 */
export const LockerInsertLockTypeEnum = {
    Key: 'key',
    Card: 'card',
    Pin: 'pin',
    Biometric: 'biometric'
} as const;
export type LockerInsertLockTypeEnum = typeof LockerInsertLockTypeEnum[keyof typeof LockerInsertLockTypeEnum];

/**
 * @export
 */
export const LockerInsertStatusEnum = {
    Available: 'available',
    InUse: 'in_use',
    Maintenance: 'maintenance',
    Broken: 'broken'
} as const;
export type LockerInsertStatusEnum = typeof LockerInsertStatusEnum[keyof typeof LockerInsertStatusEnum];


/**
 * Check if a given object implements the LockerInsert interface.
 */
export function instanceOfLockerInsert(value: object): value is LockerInsert {
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    return true;
}

export function LockerInsertFromJSON(json: any): LockerInsert {
    return LockerInsertFromJSONTyped(json, false);
}

export function LockerInsertFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockerInsert {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lockerCode': json['lockerCode'],
        'area': json['area'] == null ? undefined : json['area'],
        'size': json['size'] == null ? undefined : json['size'],
        'type': json['type'] == null ? undefined : json['type'],
        'lockType': json['lockType'] == null ? undefined : json['lockType'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'branchId': json['branchId'] == null ? undefined : json['branchId'],
    };
}

export function LockerInsertToJSON(json: any): LockerInsert {
    return LockerInsertToJSONTyped(json, false);
}

export function LockerInsertToJSONTyped(value?: LockerInsert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'area': value['area'],
        'size': value['size'],
        'type': value['type'],
        'lockType': value['lockType'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
        'branchId': value['branchId'],
    };
}

