/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Branch } from './Branch';
import {
    BranchFromJSON,
    BranchFromJSONTyped,
    BranchToJSON,
    BranchToJSONTyped,
} from './Branch';

/**
 * 
 * @export
 * @interface LockerWithRelations
 */
export interface LockerWithRelations {
    /**
     * 
     * @type {number}
     * @memberof LockerWithRelations
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    area: string | null;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    size: LockerWithRelationsSizeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    type: LockerWithRelationsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    lockType: LockerWithRelationsLockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    status: LockerWithRelationsStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LockerWithRelations
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof LockerWithRelations
     */
    userId: number | null;
    /**
     * 
     * @type {number}
     * @memberof LockerWithRelations
     */
    branchId: number | null;
    /**
     * 
     * @type {User}
     * @memberof LockerWithRelations
     */
    user: User | null;
    /**
     * 
     * @type {Branch}
     * @memberof LockerWithRelations
     */
    branch: Branch | null;
}


/**
 * @export
 */
export const LockerWithRelationsSizeEnum = {
    S: 's',
    M: 'm',
    L: 'l',
    Xl: 'xl'
} as const;
export type LockerWithRelationsSizeEnum = typeof LockerWithRelationsSizeEnum[keyof typeof LockerWithRelationsSizeEnum];

/**
 * @export
 */
export const LockerWithRelationsTypeEnum = {
    Standard: 'standard',
    Smart: 'smart'
} as const;
export type LockerWithRelationsTypeEnum = typeof LockerWithRelationsTypeEnum[keyof typeof LockerWithRelationsTypeEnum];

/**
 * @export
 */
export const LockerWithRelationsLockTypeEnum = {
    Key: 'key',
    Card: 'card',
    Pin: 'pin',
    Biometric: 'biometric'
} as const;
export type LockerWithRelationsLockTypeEnum = typeof LockerWithRelationsLockTypeEnum[keyof typeof LockerWithRelationsLockTypeEnum];

/**
 * @export
 */
export const LockerWithRelationsStatusEnum = {
    Available: 'available',
    InUse: 'in_use',
    Maintenance: 'maintenance',
    Broken: 'broken'
} as const;
export type LockerWithRelationsStatusEnum = typeof LockerWithRelationsStatusEnum[keyof typeof LockerWithRelationsStatusEnum];


/**
 * Check if a given object implements the LockerWithRelations interface.
 */
export function instanceOfLockerWithRelations(value: object): value is LockerWithRelations {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    if (!('area' in value) || value['area'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('lockType' in value) || value['lockType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('branchId' in value) || value['branchId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('branch' in value) || value['branch'] === undefined) return false;
    return true;
}

export function LockerWithRelationsFromJSON(json: any): LockerWithRelations {
    return LockerWithRelationsFromJSONTyped(json, false);
}

export function LockerWithRelationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockerWithRelations {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lockerCode': json['lockerCode'],
        'area': json['area'],
        'size': json['size'],
        'type': json['type'],
        'lockType': json['lockType'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'userId': json['userId'],
        'branchId': json['branchId'],
        'user': UserFromJSON(json['user']),
        'branch': BranchFromJSON(json['branch']),
    };
}

export function LockerWithRelationsToJSON(json: any): LockerWithRelations {
    return LockerWithRelationsToJSONTyped(json, false);
}

export function LockerWithRelationsToJSONTyped(value?: LockerWithRelations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'area': value['area'],
        'size': value['size'],
        'type': value['type'],
        'lockType': value['lockType'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
        'branchId': value['branchId'],
        'user': UserToJSON(value['user']),
        'branch': BranchToJSON(value['branch']),
    };
}

