/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockerInput
 */
export interface LockerInput {
    /**
     * 
     * @type {number}
     * @memberof LockerInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    lockerCode: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof LockerInput
     */
    createdAt: string | null;
    /**
     * 
     * @type {number}
     * @memberof LockerInput
     */
    userId: number | null;
}

/**
 * Check if a given object implements the LockerInput interface.
 */
export function instanceOfLockerInput(value: object): value is LockerInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lockerCode' in value) || value['lockerCode'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LockerInputFromJSON(json: any): LockerInput {
    return LockerInputFromJSONTyped(json, false);
}

export function LockerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockerInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lockerCode': json['lockerCode'],
        'location': json['location'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'userId': json['userId'],
    };
}

export function LockerInputToJSON(json: any): LockerInput {
    return LockerInputToJSONTyped(json, false);
}

export function LockerInputToJSONTyped(value?: LockerInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lockerCode': value['lockerCode'],
        'location': value['location'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'userId': value['userId'],
    };
}

