/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginBodyInput
 */
export interface LoginBodyInput {
    /**
     * 
     * @type {string}
     * @memberof LoginBodyInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginBodyInput
     */
    password: string;
}

/**
 * Check if a given object implements the LoginBodyInput interface.
 */
export function instanceOfLoginBodyInput(value: object): value is LoginBodyInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginBodyInputFromJSON(json: any): LoginBodyInput {
    return LoginBodyInputFromJSONTyped(json, false);
}

export function LoginBodyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginBodyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginBodyInputToJSON(json: any): LoginBodyInput {
    return LoginBodyInputToJSONTyped(json, false);
}

export function LoginBodyInputToJSONTyped(value?: LoginBodyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

