/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInput } from './UserInput';
import {
    UserInputFromJSON,
    UserInputFromJSONTyped,
    UserInputToJSON,
    UserInputToJSONTyped,
} from './UserInput';

/**
 * 
 * @export
 * @interface LoginResponseInput
 */
export interface LoginResponseInput {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseInput
     */
    token: string;
    /**
     * 
     * @type {UserInput}
     * @memberof LoginResponseInput
     */
    user: UserInput;
}

/**
 * Check if a given object implements the LoginResponseInput interface.
 */
export function instanceOfLoginResponseInput(value: object): value is LoginResponseInput {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function LoginResponseInputFromJSON(json: any): LoginResponseInput {
    return LoginResponseInputFromJSONTyped(json, false);
}

export function LoginResponseInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseInput {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'user': UserInputFromJSON(json['user']),
    };
}

export function LoginResponseInputToJSON(json: any): LoginResponseInput {
    return LoginResponseInputToJSONTyped(json, false);
}

export function LoginResponseInputToJSONTyped(value?: LoginResponseInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'user': UserInputToJSON(value['user']),
    };
}

