/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedLockerMeta } from './PaginatedLockerMeta';
import {
    PaginatedLockerMetaFromJSON,
    PaginatedLockerMetaFromJSONTyped,
    PaginatedLockerMetaToJSON,
    PaginatedLockerMetaToJSONTyped,
} from './PaginatedLockerMeta';
import type { Branch } from './Branch';
import {
    BranchFromJSON,
    BranchFromJSONTyped,
    BranchToJSON,
    BranchToJSONTyped,
} from './Branch';

/**
 * 
 * @export
 * @interface PaginatedBranch
 */
export interface PaginatedBranch {
    /**
     * 
     * @type {Array<Branch>}
     * @memberof PaginatedBranch
     */
    data: Array<Branch>;
    /**
     * 
     * @type {PaginatedLockerMeta}
     * @memberof PaginatedBranch
     */
    meta: PaginatedLockerMeta;
}

/**
 * Check if a given object implements the PaginatedBranch interface.
 */
export function instanceOfPaginatedBranch(value: object): value is PaginatedBranch {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PaginatedBranchFromJSON(json: any): PaginatedBranch {
    return PaginatedBranchFromJSONTyped(json, false);
}

export function PaginatedBranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBranch {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BranchFromJSON)),
        'meta': PaginatedLockerMetaFromJSON(json['meta']),
    };
}

export function PaginatedBranchToJSON(json: any): PaginatedBranch {
    return PaginatedBranchToJSONTyped(json, false);
}

export function PaginatedBranchToJSONTyped(value?: PaginatedBranch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BranchToJSON)),
        'meta': PaginatedLockerMetaToJSON(value['meta']),
    };
}

