/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationQuery
 */
export interface PaginationQuery {
    /**
     * 
     * @type {string}
     * @memberof PaginationQuery
     */
    p: string;
    /**
     * 
     * @type {number}
     * @memberof PaginationQuery
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationQuery
     */
    pageSize: number;
}

/**
 * Check if a given object implements the PaginationQuery interface.
 */
export function instanceOfPaginationQuery(value: object): value is PaginationQuery {
    if (!('p' in value) || value['p'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    return true;
}

export function PaginationQueryFromJSON(json: any): PaginationQuery {
    return PaginationQueryFromJSONTyped(json, false);
}

export function PaginationQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'p': json['p'],
        'page': json['page'],
        'pageSize': json['pageSize'],
    };
}

export function PaginationQueryToJSON(json: any): PaginationQuery {
    return PaginationQueryToJSONTyped(json, false);
}

export function PaginationQueryToJSONTyped(value?: PaginationQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'p': value['p'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

