/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedLockerInputMeta
 */
export interface PaginatedLockerInputMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLockerInputMeta
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedLockerInputMeta
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedLockerInputMeta
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedLockerInputMeta
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PaginatedLockerInputMeta interface.
 */
export function instanceOfPaginatedLockerInputMeta(value: object): value is PaginatedLockerInputMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PaginatedLockerInputMetaFromJSON(json: any): PaginatedLockerInputMeta {
    return PaginatedLockerInputMetaFromJSONTyped(json, false);
}

export function PaginatedLockerInputMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLockerInputMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'totalPages': json['totalPages'],
    };
}

export function PaginatedLockerInputMetaToJSON(json: any): PaginatedLockerInputMeta {
    return PaginatedLockerInputMetaToJSONTyped(json, false);
}

export function PaginatedLockerInputMetaToJSONTyped(value?: PaginatedLockerInputMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

