/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationQueryInput
 */
export interface PaginationQueryInput {
    /**
     * 
     * @type {string}
     * @memberof PaginationQueryInput
     */
    p?: string;
    /**
     * 
     * @type {number}
     * @memberof PaginationQueryInput
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationQueryInput
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the PaginationQueryInput interface.
 */
export function instanceOfPaginationQueryInput(value: object): value is PaginationQueryInput {
    return true;
}

export function PaginationQueryInputFromJSON(json: any): PaginationQueryInput {
    return PaginationQueryInputFromJSONTyped(json, false);
}

export function PaginationQueryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationQueryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'p': json['p'] == null ? undefined : json['p'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function PaginationQueryInputToJSON(json: any): PaginationQueryInput {
    return PaginationQueryInputToJSONTyped(json, false);
}

export function PaginationQueryInputToJSONTyped(value?: PaginationQueryInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'p': value['p'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

