/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateInput
 */
export interface UserUpdateInput {
    /**
     * 
     * @type {number}
     * @memberof UserUpdateInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    role?: UserUpdateInputRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    createdAt?: string;
}


/**
 * @export
 */
export const UserUpdateInputRoleEnum = {
    Guest: 'guest',
    User: 'user',
    Admin: 'admin'
} as const;
export type UserUpdateInputRoleEnum = typeof UserUpdateInputRoleEnum[keyof typeof UserUpdateInputRoleEnum];


/**
 * Check if a given object implements the UserUpdateInput interface.
 */
export function instanceOfUserUpdateInput(value: object): value is UserUpdateInput {
    return true;
}

export function UserUpdateInputFromJSON(json: any): UserUpdateInput {
    return UserUpdateInputFromJSONTyped(json, false);
}

export function UserUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'role': json['role'] == null ? undefined : json['role'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function UserUpdateInputToJSON(json: any): UserUpdateInput {
    return UserUpdateInputToJSONTyped(json, false);
}

export function UserUpdateInputToJSONTyped(value?: UserUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
        'email': value['email'],
        'password': value['password'],
        'role': value['role'],
        'createdAt': value['createdAt'],
    };
}

