/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInsert
 */
export interface UserInsert {
    /**
     * 
     * @type {number}
     * @memberof UserInsert
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserInsert
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInsert
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserInsert
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserInsert
     */
    role?: UserInsertRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserInsert
     */
    createdAt?: string;
}


/**
 * @export
 */
export const UserInsertRoleEnum = {
    Guest: 'guest',
    User: 'user',
    Admin: 'admin'
} as const;
export type UserInsertRoleEnum = typeof UserInsertRoleEnum[keyof typeof UserInsertRoleEnum];


/**
 * Check if a given object implements the UserInsert interface.
 */
export function instanceOfUserInsert(value: object): value is UserInsert {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserInsertFromJSON(json: any): UserInsert {
    return UserInsertFromJSONTyped(json, false);
}

export function UserInsertFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInsert {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'],
        'password': json['password'],
        'role': json['role'] == null ? undefined : json['role'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function UserInsertToJSON(json: any): UserInsert {
    return UserInsertToJSONTyped(json, false);
}

export function UserInsertToJSONTyped(value?: UserInsert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
        'email': value['email'],
        'password': value['password'],
        'role': value['role'],
        'createdAt': value['createdAt'],
    };
}

