/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LockerInput } from './LockerInput';
import {
    LockerInputFromJSON,
    LockerInputFromJSONTyped,
    LockerInputToJSON,
    LockerInputToJSONTyped,
} from './LockerInput';

/**
 * 
 * @export
 * @interface UserWithRelationsInput
 */
export interface UserWithRelationsInput {
    /**
     * 
     * @type {number}
     * @memberof UserWithRelationsInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserWithRelationsInput
     */
    fullName: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserWithRelationsInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRelationsInput
     */
    role: UserWithRelationsInputRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserWithRelationsInput
     */
    createdAt: string;
    /**
     * 
     * @type {LockerInput}
     * @memberof UserWithRelationsInput
     */
    locker: LockerInput | null;
}


/**
 * @export
 */
export const UserWithRelationsInputRoleEnum = {
    Guest: 'guest',
    User: 'user',
    Admin: 'admin'
} as const;
export type UserWithRelationsInputRoleEnum = typeof UserWithRelationsInputRoleEnum[keyof typeof UserWithRelationsInputRoleEnum];


/**
 * Check if a given object implements the UserWithRelationsInput interface.
 */
export function instanceOfUserWithRelationsInput(value: object): value is UserWithRelationsInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('locker' in value) || value['locker'] === undefined) return false;
    return true;
}

export function UserWithRelationsInputFromJSON(json: any): UserWithRelationsInput {
    return UserWithRelationsInputFromJSONTyped(json, false);
}

export function UserWithRelationsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithRelationsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': json['fullName'],
        'email': json['email'],
        'role': json['role'],
        'createdAt': json['createdAt'],
        'locker': LockerInputFromJSON(json['locker']),
    };
}

export function UserWithRelationsInputToJSON(json: any): UserWithRelationsInput {
    return UserWithRelationsInputToJSONTyped(json, false);
}

export function UserWithRelationsInputToJSONTyped(value?: UserWithRelationsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
        'email': value['email'],
        'role': value['role'],
        'createdAt': value['createdAt'],
        'locker': LockerInputToJSON(value['locker']),
    };
}

