/* tslint:disable */
/* eslint-disable */
/**
 * Smart Locker API
 * API quản lý tủ đồ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInsertInput
 */
export interface UserInsertInput {
    /**
     * 
     * @type {number}
     * @memberof UserInsertInput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserInsertInput
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInsertInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserInsertInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserInsertInput
     */
    role?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInsertInput
     */
    createdAt?: string | null;
}

/**
 * Check if a given object implements the UserInsertInput interface.
 */
export function instanceOfUserInsertInput(value: object): value is UserInsertInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserInsertInputFromJSON(json: any): UserInsertInput {
    return UserInsertInputFromJSONTyped(json, false);
}

export function UserInsertInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInsertInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'],
        'password': json['password'],
        'role': json['role'] == null ? undefined : json['role'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function UserInsertInputToJSON(json: any): UserInsertInput {
    return UserInsertInputToJSONTyped(json, false);
}

export function UserInsertInputToJSONTyped(value?: UserInsertInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
        'email': value['email'],
        'password': value['password'],
        'role': value['role'],
        'createdAt': value['createdAt'],
    };
}

